import "./globals.css";
import MovieCompFooter from "./components/MovieCompFooter";
import AppProvider from "./components/AppProvider/AppProvider";
export const metadata = {
  title: "movie-app",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AppProvider children={children} />
        <MovieCompFooter></MovieCompFooter>
      </body>
    </html>
  );
}
