"use client";
import { useState } from "react";
import "./globals.css";
import { ticketContext } from "./ticketContextProvider";

export const metadata = {
  title: "movie-app",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const [tickets, setTickets] = useState([]);
  return (
    <html lang="en">
      <body>
        <ticketContext.Provider value={{ tickets, setTickets }}>
          {children}
        </ticketContext.Provider>
      </body>
    </html>
  );
}
