import "./globals.css";
import AuthProvider from "./components/AuthProvider/AuthProvider";
import TicketProvider from "./components/TicketContextProvider/TicketProvider";
export const metadata = {
  title: "movie-app",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <TicketProvider>
          <AuthProvider> {children}</AuthProvider>
        </TicketProvider>
      </body>
    </html>
  );
}
